version: '3'
services:
  strapi:
    container_name: backend
    image: backend:staging
    links:
      - postgres:postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
